#!/bin/bash

# AERO_Agent Weekly Usage Report
# This script generates a comprehensive weekly usage report

REPORT_DIR="reports"
DATE=$(date +%Y%m%d_%H%M)
WEEK_START=$(date -d "7 days ago" +%Y%m%d)
WEEK_END=$(date +%Y%m%d)

echo "📊 AERO_Agent Weekly Usage Report"
echo "================================"
echo "📅 Period: $WEEK_START to $WEEK_END"
echo "⏰ Generated: $(date)"
echo ""

# Create reports directory
mkdir -p "$REPORT_DIR"

# 1. Claude Code Daily Summary
echo "1️⃣ Generating Claude Code Daily Summary..."
npx ccusage daily --since "$WEEK_START" --until "$WEEK_END" --breakdown \
  > "$REPORT_DIR/claude-daily-${DATE}.txt" 2>/dev/null

# 2. Monthly Overview
echo "2️⃣ Generating Monthly Overview..."
npx ccusage monthly --breakdown --json \
  > "$REPORT_DIR/claude-monthly-${DATE}.json" 2>/dev/null

# 3. Session Analysis
echo "3️⃣ Generating Session Analysis..."
npx ccusage session --since "$WEEK_START" \
  > "$REPORT_DIR/claude-sessions-${DATE}.txt" 2>/dev/null

# 4. Codex Analysis
echo "4️⃣ Generating Codex Analysis..."
if [ -f "$HOME/.codex/log/codex-tui.log" ]; then
    ./scripts/analyze-codex-usage.sh \
      > "$REPORT_DIR/codex-analysis-${DATE}.txt" 2>/dev/null
else
    echo "❌ No Codex logs found" > "$REPORT_DIR/codex-analysis-${DATE}.txt"
fi

# 5. Generate Summary Report
echo "5️⃣ Generating Summary Report..."
cat > "$REPORT_DIR/weekly-summary-${DATE}.md" << EOF
# AERO_Agent Weekly Usage Report

**Period:** $WEEK_START to $WEEK_END
**Generated:** $(date)

## 📊 Claude Code Usage

### Summary
$(tail -20 "$REPORT_DIR/claude-daily-${DATE}.txt" 2>/dev/null | head -15)

### Cost Breakdown
$(npx ccusage monthly --breakdown 2>/dev/null | grep -E "(Total|Cost)" | tail -2)

## 🤖 Codex Usage

### Tool Usage
$(grep -E "(Tool calls|Total errors)" "$REPORT_DIR/codex-analysis-${DATE}.txt" 2>/dev/null)

## 📈 Recommendations

### Cost Optimization
- Review high-cost sessions in the daily summary
- Consider using more cache-efficient prompts
- Monitor model usage distribution

### Usage Patterns
- Identify peak usage hours
- Review session durations
- Optimize workflow efficiency

## 📁 Report Files

- \`claude-daily-${DATE}.txt\` - Daily usage breakdown
- \`claude-monthly-${DATE}.json\` - Monthly overview (JSON)
- \`claude-sessions-${DATE}.txt\` - Session analysis
- \`codex-analysis-${DATE}.txt\` - Codex usage analysis

---
*Generated by AERO_Agent Usage Monitor*
EOF

# 6. Display summary
echo ""
echo "✅ Weekly report generated!"
echo ""
echo "📁 Report files created in: $REPORT_DIR/"
echo ""
echo "📄 Summary Report:"
echo "   $REPORT_DIR/weekly-summary-${DATE}.md"
echo ""
echo "📊 Individual Reports:"
echo "   - Claude Daily: $REPORT_DIR/claude-daily-${DATE}.txt"
echo "   - Claude Monthly: $REPORT_DIR/claude-monthly-${DATE}.json"
echo "   - Claude Sessions: $REPORT_DIR/claude-sessions-${DATE}.txt"
echo "   - Codex Analysis: $REPORT_DIR/codex-analysis-${DATE}.txt"
echo ""

# 7. Show quick stats
echo "🔍 Quick Statistics:"
echo "==================="
if command -v npx &> /dev/null; then
    echo "💰 Total Cost (Month): $(npx ccusage monthly 2>/dev/null | grep 'Total' | awk '{print $NF}' || echo 'N/A')"
    echo "📊 Total Tokens (Month): $(npx ccusage monthly 2>/dev/null | grep 'Total' | awk '{print $(NF-2)}' || echo 'N/A')"
fi

if [ -f "$HOME/.codex/log/codex-tui.log" ]; then
    TOTAL_CALLS=$(grep -c "ToolCall" "$HOME/.codex/log/codex-tui.log")
    echo "🔧 Total Codex Tool Calls: $TOTAL_CALLS"
fi

echo ""
echo "💡 To view the summary report:"
echo "   cat $REPORT_DIR/weekly-summary-${DATE}.md"
echo ""
echo "🗑️  To clean old reports (older than 30 days):"
echo "   find $REPORT_DIR/ -name '*.txt' -mtime +30 -delete"
echo "   find $REPORT_DIR/ -name '*.json' -mtime +30 -delete"
echo "   find $REPORT_DIR/ -name '*.md' -mtime +30 -delete"
